### ISSUE TITLE
Broken javascript content

### ISSUE THREAD

**Issue by fco64** [tburry/pquery#7]
Hi,
First, sorry for my elementary English.
I'll found that this istruction (gan_node_html.php line 465):
function getPlainText() {
		return preg_replace('`\s+`', ' ', html_entity_decode($this->toString(true, true, true), ENT_QUOTES));
}
will breaks embedded javascript with double slash comment.
infact, the pattern \s+ will match spaces and newlines, so code block is trasformed into a single line entirely broken by comment starting with '//'
Changing pattern in  '`\ +`'  (a space) trasformation works great.
Hope this can help somebody
Franco

**Comment by tburry** [comment]
I'm not sure if this is actually a bug and without a better example I'm going to have to close this issue.
